import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Sidenav from "@/components/Sidenav";
// import Sidenav from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <div className="flex">
          <Sidenav />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
